In [15]:
import numpy as np
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(notre_tableau)
type(notre_tableau)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


numpy.ndarray

In [16]:
mon_array_bidimensionnel=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mon_array_bidimensionnel)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# Pour selectionner la valeur de la troisiéme colonne premiére ligne
print(mon_array_bidimensionnel[0][2])
print(mon_array_bidimensionnel[0, 2])

# Pour selectionner la premiére ligne
print(mon_array_bidimensionnel[:,0])

# Pour selectionner le premiére colonne
print(mon_array_bidimensionnel[0,:])

3
3
[1 4 7]
[1 2 3]


In [18]:
mon_array_bidimensionnel[0, 0]="texte"

ValueError: invalid literal for int() with base 10: 'texte'

In [19]:
mon_array_bidimensionnel.dtype

dtype('int64')

In [20]:
mon_array_bidimensionnel=np.array([[1.5,2,3],[4,5.2,6],[7,8,9.1]], dtype = float)
print(mon_array_bidimensionnel)
mon_array_bidimensionnel.dtype

[[1.5 2.  3. ]
 [4.  5.2 6. ]
 [7.  8.  9.1]]


dtype('float64')

In [21]:
#Créer un ndarray grâce à des fonctions NumPy

In [22]:
import numpy as np
# np.zeros() permet de créer un ndarray dont l'esemble des éléments correspondent à la valeur zéro.
mon_array_zeros=np.zeros((4,6))
print(mon_array_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [23]:
import numpy as np
mon_array_ones=np.ones((4,6), dtype=int)
print(mon_array_ones)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [24]:
import numpy as np
# np.random/random() permet de créer un tableau avec des éléments aléatoire
mon_array_random = np.random.random((4,2))
print(mon_array_random)

[[0.9628844  0.32623065]
 [0.7631174  0.06782361]
 [0.33581892 0.12166002]
 [0.39804896 0.76283897]]


In [25]:
import numpy as np

iris=np.genfromtxt("/home/simplon/Documents/Python_cours/Introduction_a_NumPy/iris.csv", delimiter=";", skip_header=True, encoding='latin-1')
print(iris)
print(iris.dtype)
type(iris)

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

numpy.ndarray

In [26]:
import numpy as np
np.savetxt("/home/simplon/Documents/Python_cours/Introduction_a_NumPy/iris_2.csv", iris, delimiter=";")

In [27]:
# 1.2 Indexation
# 1.2.1 Indexation simple

In [28]:
iris[2,1]

3.2

In [29]:
iris[2,1]=4
iris[2,1]

4.0

In [30]:
iris[2,1]=3.2
iris[2,1]

3.2

In [31]:
# Indexation booléenne
# Rappels : les opérateurs relationnels, permettent de comparer des valeurs : ==, !=, <, >, <=, >=
# si on ne souhaite garder que les valeurs supérieures à 2 dans ce tableau, peu importe la colonne:

In [32]:
iris[iris>2]

array([5.1, 3.5, 4.9, 3. , 4.7, 3.2, 4.6, 3.1, 5. , 3.6, 5.4, 3.9, 4.6,
       3.4, 5. , 3.4, 4.4, 2.9, 4.9, 3.1, 5.4, 3.7, 4.8, 3.4, 4.8, 3. ,
       4.3, 3. , 5.8, 4. , 5.7, 4.4, 5.4, 3.9, 5.1, 3.5, 5.7, 3.8, 5.1,
       3.8, 5.4, 3.4, 5.1, 3.7, 4.6, 3.6, 5.1, 3.3, 4.8, 3.4, 5. , 3. ,
       5. , 3.4, 5.2, 3.5, 5.2, 3.4, 4.7, 3.2, 4.8, 3.1, 5.4, 3.4, 5.2,
       4.1, 5.5, 4.2, 4.9, 3.1, 5. , 3.2, 5.5, 3.5, 4.9, 3.6, 4.4, 3. ,
       5.1, 3.4, 5. , 3.5, 4.5, 2.3, 4.4, 3.2, 5. , 3.5, 5.1, 3.8, 4.8,
       3. , 5.1, 3.8, 4.6, 3.2, 5.3, 3.7, 5. , 3.3, 7. , 3.2, 4.7, 6.4,
       3.2, 4.5, 6.9, 3.1, 4.9, 5.5, 2.3, 4. , 6.5, 2.8, 4.6, 5.7, 2.8,
       4.5, 6.3, 3.3, 4.7, 4.9, 2.4, 3.3, 6.6, 2.9, 4.6, 5.2, 2.7, 3.9,
       5. , 3.5, 5.9, 3. , 4.2, 6. , 2.2, 4. , 6.1, 2.9, 4.7, 5.6, 2.9,
       3.6, 6.7, 3.1, 4.4, 5.6, 3. , 4.5, 5.8, 2.7, 4.1, 6.2, 2.2, 4.5,
       5.6, 2.5, 3.9, 5.9, 3.2, 4.8, 6.1, 2.8, 4. , 6.3, 2.5, 4.9, 6.1,
       2.8, 4.7, 6.4, 2.9, 4.3, 6.6, 3. , 4.4, 6.8, 2.8, 4.8, 6.

In [33]:
iris[iris>2].shape

(472,)

In [34]:
iris[iris>2].shape[0]

472

In [35]:
# L'expression booléenne qui suit génére un nouveau tableau, de même dimension que le tableau iris, mais qui contient unqiment des booléens, True ou False.

In [36]:
iris > 2

array([[ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, Fal

In [37]:
# Pour appliquer la condition sur la colonne particuliére du tableau, il faut la sélectionner en écrivant le masque booléen de la manière suivante.

In [38]:
iris[iris[:, 0] >5]

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4.1, 1.5, 0.1, 1. ],
       [5.5, 4.2, 1.4, 0.2, 1. ],
       [5.5, 3.5, 1.3, 0.2, 1. ],
       [5.1, 3.4, 1.5, 0.2, 1. ],
       [5.1, 3.8, 1.9, 0.4, 1. ],
       [5.1, 3.8, 1.6, 0.2, 1. ],
       [5.3, 3.7, 1.5, 0.2, 1. ],
       [7. , 3.2, 4.7, 1.4, 2. ],
       [6.4, 3.2, 4.5, 1.5, 2. ],
       [6.9, 3.1, 4.9, 1.5, 2. ],
       [5.5, 2.3, 4. , 1.3, 2. ],
       [6.5, 2.8, 4.6, 1.5, 2. ],
       [5.7, 2.8, 4.5, 1.3, 2. ],
       [6.3, 3.3, 4.7, 1.6, 2. ],
       [6.6, 2

In [39]:
# conserver les type du 3 type
iris[iris[:, 4] == 3]

array([[6.3, 3.3, 6. , 2.5, 3. ],
       [5.8, 2.7, 5.1, 1.9, 3. ],
       [7.1, 3. , 5.9, 2.1, 3. ],
       [6.3, 2.9, 5.6, 1.8, 3. ],
       [6.5, 3. , 5.8, 2.2, 3. ],
       [7.6, 3. , 6.6, 2.1, 3. ],
       [4.9, 2.5, 4.5, 1.7, 3. ],
       [7.3, 2.9, 6.3, 1.8, 3. ],
       [6.7, 2.5, 5.8, 1.8, 3. ],
       [7.2, 3.6, 6.1, 2.5, 3. ],
       [6.5, 3.2, 5.1, 2. , 3. ],
       [6.4, 2.7, 5.3, 1.9, 3. ],
       [6.8, 3. , 5.5, 2.1, 3. ],
       [5.7, 2.5, 5. , 2. , 3. ],
       [5.8, 2.8, 5.1, 2.4, 3. ],
       [6.4, 3.2, 5.3, 2.3, 3. ],
       [6.5, 3. , 5.5, 1.8, 3. ],
       [7.7, 3.8, 6.7, 2.2, 3. ],
       [7.7, 2.6, 6.9, 2.3, 3. ],
       [6. , 2.2, 5. , 1.5, 3. ],
       [6.9, 3.2, 5.7, 2.3, 3. ],
       [5.6, 2.8, 4.9, 2. , 3. ],
       [7.7, 2.8, 6.7, 2. , 3. ],
       [6.3, 2.7, 4.9, 1.8, 3. ],
       [6.7, 3.3, 5.7, 2.1, 3. ],
       [7.2, 3.2, 6. , 1.8, 3. ],
       [6.2, 2.8, 4.8, 1.8, 3. ],
       [6.1, 3. , 4.9, 1.8, 3. ],
       [6.4, 2.8, 5.6, 2.1, 3. ],
       [7.2, 3

# Ici nous venons de sélectionner uniquement les valeurs ou la longueur des sépales est supérieure à 5 centimèetres, c'est-à-dire ou les valeurs de la premiére colonne sont supérieures à 5

# Dans la cellules qui suit on isole la parti "iris[:, 0] > 5". C'est cette partie qui génére un ndarray à 1 dimension contenant 150 valeurs (car il y a 150 lignes dans le tableau). Ainsi, Python sait qu'il doit garder uniquement les lignes à l'indice ou la valeur est à True dans "iris[: , 0] > 5".

In [42]:
iris[:, 0] > 5

array([ True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True, False, False, False,
        True,  True, False, False,  True,  True,  True, False, False,
        True, False, False,  True, False, False, False, False,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

# Fancy indexing (littéralement indexation fantaisie)

# Le but est simple : donner un tableau d'indices (ou une liste d'indices) entre crochets à notre ndarray pour sélectionner plusieurs éléments non consécutifs.

In [47]:
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("Contenu de notre_tableau :")
print(notre_tableau)
print("Nouveau tableau aprés fancy indexing :")
print(notre_tableau[np.array([[4,10,5], [12,8,9]])])

Contenu de notre_tableau :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Nouveau tableau aprés fancy indexing :
[[ 5 11  6]
 [13  9 10]]


In [52]:
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("Contenu de notre_tableau :")
print(notre_tableau)
print("Nouveau tableau aprés fancy indexing :")
indices = np.array([[4,10,5], [12,8,9]])
print(notre_tableau[indices])

Contenu de notre_tableau :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Nouveau tableau aprés fancy indexing :
[[ 5 11  6]
 [13  9 10]]


# 1.3 Accéder aux éléements par tranche (sclicing)
# Slicing sur un tableau NumPy à 1 dimension

In [53]:
# Les trois premier éléments
notre_tableau[:3]

array([1, 2, 3])

In [54]:
# Les derniers éléments à partir de l'index 10
notre_tableau[10:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [55]:
# Du troisiéme aux spetiéme éléments
notre_tableau[3:7]

array([4, 5, 6, 7])

In [56]:
# Tout les éléments avec un pas de deux
notre_tableau[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# 1.3.2 Slicing sur un tableau NumPy à 2 dimensions

In [58]:
# Ici on sélectionne les deux premiére lignes des 4 premiére colonnes.
iris[:2,:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [59]:
# Les derniéres lignes à partir de l'index 145 des dernières colonnes à partir de l'index 2.
iris[145:,2:]

array([[5.2, 2.3, 3. ],
       [5. , 1.9, 3. ],
       [5.2, 2. , 3. ],
       [5.4, 2.3, 3. ],
       [5.1, 1.8, 3. ]])

In [60]:
# Affiche toutes les colonnes de la ligne 0, la premiére ligne
iris[0,:]

array([5.1, 3.5, 1.4, 0.2, 1. ])

In [61]:
iris[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [62]:
# Affiche toute les colonnes de la dernière ligne. 
iris[-1,:]

array([5.9, 3. , 5.1, 1.8, 3. ])

# 1.4 Notion de vue et copie

In [64]:
sous_tableau=notre_tableau[:5]
sous_tableau

array([1, 2, 3, 4, 5])

In [65]:
sous_tableau[0]=10
sous_tableau

array([10,  2,  3,  4,  5])

In [66]:
notre_tableau

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# La première valeur est devenue 10 aussi alors que nous avons modifié l'objet sous_tableau et non pas notre_tableau. 
# Lorsqu'on fait du slicing sur un tableau, ce qu'il retourne, c'est une vue du tableau et non pas une copie du tableau. Ce n'est pas un nouvel ndarray

In [68]:
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
sous_tableau=notre_tableau[:5].copy()
sous_tableau[0]=10
print(sous_tableau)
print(notre_tableau)

[10  2  3  4  5]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


# 2. Les opérations mathématiques avec NumPy
# 2.1 Les opérations arithmétiques

In [70]:
mon_tableau=np.array([[10,11,12],[13,14,15],[16,17,18]])
mon_tableau

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [71]:
import numpy as np 
np.add(mon_tableau,10)

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [72]:
import numpy as np 
np.multiply(mon_tableau,20)

array([[200, 220, 240],
       [260, 280, 300],
       [320, 340, 360]])

In [74]:
mon_tableau2=np.array([10,20,30])
mon_tableau2
mon_tableau

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [75]:
import numpy as np 
np.subtract(mon_tableau,mon_tableau2)

array([[  0,  -9, -18],
       [  3,  -6, -15],
       [  6,  -3, -12]])

In [76]:
mon_tableau3=np.array([[1,2,3],[4,5,6],[7,8,9]])
mon_tableau3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.multiply(mon_tableau,mon_tableau3)

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

# 2.2 Les fonctions d'agrégations

In [79]:
import numpy as np 
print("Somme sur l'ensemble des éléements :")
print(np.sum(iris))

# axis = 0 signifie qu'on veut effectuer le calcul par colonne
# et axis = 1 signifie qu'on veut effectuer le calcul par ligne. 
print("Somme par colonne :")
print(np.sum(iris, axis=0))
print("Somme par ligne :")
print(np.sum(iris, axis=1))

Somme sur l'ensemble des éléements :
2378.7
Somme par colonne :
[876.5 458.6 563.7 179.9 300. ]
Somme par ligne :
[11.2 10.5 10.4 10.4 11.2 12.4 10.7 11.1  9.9 10.6 11.8 11.  10.3  9.5
 12.2 13.  12.  11.3 12.5 11.7 11.7 11.7 10.4 11.6 11.3 10.8 11.4 11.4
 11.2 10.7 10.7 11.7 11.9 12.3 10.7 10.6 11.5 11.   9.9 11.2 11.1  9.4
 10.1 11.7 12.2 10.5 11.7 10.4 11.7 10.9 18.3 17.6 18.4 15.1 17.4 16.3
 17.9 13.6 17.4 15.2 13.5 16.6 15.2 17.1 15.4 17.6 16.6 15.6 16.4 15.1
 17.7 16.2 17.2 16.8 16.9 17.4 17.8 18.4 16.9 14.8 14.8 14.6 15.6 17.4
 16.4 17.5 18.  16.3 16.  15.3 15.7 17.1 15.6 13.6 15.8 16.1 16.1 16.7
 13.7 15.9 21.1 18.5 21.1 19.6 20.5 22.3 16.6 21.3 19.8 22.4 19.8 19.3
 20.4 18.2 19.1 20.2 19.8 23.4 22.5 17.7 21.1 18.3 22.2 18.7 20.8 21.2
 18.6 18.8 19.9 20.6 21.2 23.1 20.  18.7 18.7 22.1 20.7 19.8 18.6 20.5
 20.8 20.4 18.5 21.2 21.2 20.2 18.7 19.7 20.3 18.8]


In [80]:
import numpy as np 
print(np.mean(iris, axis=0))
print(np.std(iris, axis=0))

[5.84333333 3.05733333 3.758      1.19933333 2.        ]
[0.82530129 0.43441097 1.75940407 0.75969263 0.81649658]


In [81]:
import numpy as np 
print(np.max(iris, axis=0))

[7.9 4.4 6.9 2.5 3. ]


In [84]:
iris3 = iris[iris[:,4]==3]
iris2 = iris[iris[:,4]==2]
iris1 = iris[iris[:,4]==1]
#print(iris3)
print(np.mean(iris3, axis=0))
print(np.mean(iris2, axis=0))
print(np.mean(iris1, axis=0))

[6.588 2.974 5.552 2.026 3.   ]
[5.936 2.77  4.26  1.326 2.   ]
[5.006 3.428 1.462 0.246 1.   ]


# 2. Inspecter un tableau grâce aux attributs de Numpy

In [85]:
print("Attribut size :")
print(iris.size)
print("Attribut shape :")
print("Attribut ndim :")
print(iris.ndim)
print("Attribut dtype :")
print(iris.dtype)

Attribut size :
750
Attribut shape :
Attribut ndim :
2
Attribut dtype :
float64


In [86]:
iris.T 

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

# 4 Manipulation de tableaux NumPy
# 4.1 Ajouter et supprimer des éléments d'un tableau
# 4.1.1 Ajouter des éléments dans un tableau

In [88]:
np.append(notre_tableau, [21,22,23,24,25])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [89]:
np.append(iris,[[10,10,10,10,10]], axis=0)

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [ 4.9,  3. ,  1.4,  0.2,  1. ],
       [ 4.7,  3.2,  1.3,  0.2,  1. ],
       [ 4.6,  3.1,  1.5,  0.2,  1. ],
       [ 5. ,  3.6,  1.4,  0.2,  1. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 4.6,  3.4,  1.4,  0.3,  1. ],
       [ 5. ,  3.4,  1.5,  0.2,  1. ],
       [ 4.4,  2.9,  1.4,  0.2,  1. ],
       [ 4.9,  3.1,  1.5,  0.1,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 4.8,  3.4,  1.6,  0.2,  1. ],
       [ 4.8,  3. ,  1.4,  0.1,  1. ],
       [ 4.3,  3. ,  1.1,  0.1,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 4.6,  3.6,  1. ,  0.2,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 4.8,  3.4,  1.9,  0.2,  1. ],
       [ 5. ,  3. ,  1.6,

In [90]:
import numpy
np.insert(notre_tableau, 1, 42)
# L'élément 42 a été ajouté à l'index 1,
# donc à la place de la valeur 2, et la valeur 2 se retrouve alors à l'index 2.

array([ 1, 42,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [91]:
import numpy
np.insert(notre_tableau, 1, [42,43,44,45,46])

array([ 1, 42, 43, 44, 45, 46,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 20])

In [92]:
import numpy as np 
np.insert(iris, 1, [10,10,10,10,10], axis=0)
# On vient d'insérer une ligne en deuxiéme position du tableau iris, contenant cinq valeurs

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [10. , 10. , 10. , 10. , 10. ],
       [ 4.9,  3. ,  1.4,  0.2,  1. ],
       [ 4.7,  3.2,  1.3,  0.2,  1. ],
       [ 4.6,  3.1,  1.5,  0.2,  1. ],
       [ 5. ,  3.6,  1.4,  0.2,  1. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 4.6,  3.4,  1.4,  0.3,  1. ],
       [ 5. ,  3.4,  1.5,  0.2,  1. ],
       [ 4.4,  2.9,  1.4,  0.2,  1. ],
       [ 4.9,  3.1,  1.5,  0.1,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 4.8,  3.4,  1.6,  0.2,  1. ],
       [ 4.8,  3. ,  1.4,  0.1,  1. ],
       [ 4.3,  3. ,  1.1,  0.1,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 4.6,  3.6,  1. ,  0.2,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 4.8,  3.4,  1.9,

In [93]:
import numpy as np 
np.insert(iris, 1, [10,10,10,10,10])

array([ 5.1, 10. , 10. , 10. , 10. , 10. ,  3.5,  1.4,  0.2,  1. ,  4.9,
        3. ,  1.4,  0.2,  1. ,  4.7,  3.2,  1.3,  0.2,  1. ,  4.6,  3.1,
        1.5,  0.2,  1. ,  5. ,  3.6,  1.4,  0.2,  1. ,  5.4,  3.9,  1.7,
        0.4,  1. ,  4.6,  3.4,  1.4,  0.3,  1. ,  5. ,  3.4,  1.5,  0.2,
        1. ,  4.4,  2.9,  1.4,  0.2,  1. ,  4.9,  3.1,  1.5,  0.1,  1. ,
        5.4,  3.7,  1.5,  0.2,  1. ,  4.8,  3.4,  1.6,  0.2,  1. ,  4.8,
        3. ,  1.4,  0.1,  1. ,  4.3,  3. ,  1.1,  0.1,  1. ,  5.8,  4. ,
        1.2,  0.2,  1. ,  5.7,  4.4,  1.5,  0.4,  1. ,  5.4,  3.9,  1.3,
        0.4,  1. ,  5.1,  3.5,  1.4,  0.3,  1. ,  5.7,  3.8,  1.7,  0.3,
        1. ,  5.1,  3.8,  1.5,  0.3,  1. ,  5.4,  3.4,  1.7,  0.2,  1. ,
        5.1,  3.7,  1.5,  0.4,  1. ,  4.6,  3.6,  1. ,  0.2,  1. ,  5.1,
        3.3,  1.7,  0.5,  1. ,  4.8,  3.4,  1.9,  0.2,  1. ,  5. ,  3. ,
        1.6,  0.2,  1. ,  5. ,  3.4,  1.6,  0.4,  1. ,  5.2,  3.5,  1.5,
        0.2,  1. ,  5.2,  3.4,  1.4,  0.2,  1. ,  4

# 4.1.2 Supprimer des éléments d'un tableau

In [95]:
np.delete(iris, 1, axis = 1)
# On suprime la colonne 2 (à l'index 1)

array([[5.1, 1.4, 0.2, 1. ],
       [4.9, 1.4, 0.2, 1. ],
       [4.7, 1.3, 0.2, 1. ],
       [4.6, 1.5, 0.2, 1. ],
       [5. , 1.4, 0.2, 1. ],
       [5.4, 1.7, 0.4, 1. ],
       [4.6, 1.4, 0.3, 1. ],
       [5. , 1.5, 0.2, 1. ],
       [4.4, 1.4, 0.2, 1. ],
       [4.9, 1.5, 0.1, 1. ],
       [5.4, 1.5, 0.2, 1. ],
       [4.8, 1.6, 0.2, 1. ],
       [4.8, 1.4, 0.1, 1. ],
       [4.3, 1.1, 0.1, 1. ],
       [5.8, 1.2, 0.2, 1. ],
       [5.7, 1.5, 0.4, 1. ],
       [5.4, 1.3, 0.4, 1. ],
       [5.1, 1.4, 0.3, 1. ],
       [5.7, 1.7, 0.3, 1. ],
       [5.1, 1.5, 0.3, 1. ],
       [5.4, 1.7, 0.2, 1. ],
       [5.1, 1.5, 0.4, 1. ],
       [4.6, 1. , 0.2, 1. ],
       [5.1, 1.7, 0.5, 1. ],
       [4.8, 1.9, 0.2, 1. ],
       [5. , 1.6, 0.2, 1. ],
       [5. , 1.6, 0.4, 1. ],
       [5.2, 1.5, 0.2, 1. ],
       [5.2, 1.4, 0.2, 1. ],
       [4.7, 1.6, 0.2, 1. ],
       [4.8, 1.6, 0.2, 1. ],
       [5.4, 1.5, 0.4, 1. ],
       [5.2, 1.5, 0.1, 1. ],
       [5.5, 1.4, 0.2, 1. ],
       [4.9, 1

In [96]:
np.delete(iris, [1,2,3,4], axis = 0)
# On supprime les lignes à l'index 1, 2, 3 et 4

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.6, 0.2, 1. ],
       [4.8, 3.1, 1.6, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4.1, 1.5, 0.1, 1. ],
       [5.5, 4

In [97]:
np.delete(notre_tableau, 1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

# 4.2 Diviser un tableau NumPy (split, hsplit et vsplit)
# 4.2.1 Sur un tableau à une dimension

In [99]:
notre_tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [100]:
import numpy as np 
notre_tableau1, notre_tableau2, notre_tableau3 = np.split(notre_tableau, [2, 6])
print(notre_tableau1, notre_tableau2, notre_tableau3)

[1 2] [3 4 5 6] [ 7  8  9 10 11 12 13 14 15 16 17 18 19 20]


# 4.2.2 Sur un tableau à deux dimensions.

In [103]:
tableau=np.array([[2,5,6],[9,10,11],[5,6,9]], dtype="float")
print("Avant division")
print(tableau)
tableau1, tableau2 = np.vsplit(array, [2])
print("Après division")
print(tableau1)
print(tableau2)

Avant division
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]
Après division
[[ 2.  5.  6.]
 [ 9. 10. 11.]]
[[5. 6. 9.]]


In [104]:
array= np.array([[2,5,6],[9,10,11],[5,6,9]], dtype="float")
print("Avant division")
print(array)
array1, array2 = np.hsplit(array, [2])
print("Après division")
print(array1)
print(array2)

Avant division
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]
Après division
[[ 2.  5.]
 [ 9. 10.]
 [ 5.  6.]]
[[ 6.]
 [11.]
 [ 9.]]


# 4.3 Concaténer/ combiner des tableaux
# 4.3.1 La fonction concatenate()

In [106]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9])
print(array1)
print(array2)
np.concatenate([array1, array2])

[1 2 3 4 5]
[6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
array1= np.array([[1,2,3], [4,5,6], [7,8,9]], dtype="float")
array2= np.array([[2,5,6,],[9,10,11],[5,6,9]], dtype="float")
print(array1)
print(array2)
np.concatenate([array1, array2])

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 2.,  5.,  6.],
       [ 9., 10., 11.],
       [ 5.,  6.,  9.]])

In [108]:
array3= np.array([[4,10,13],[7,14,15]], dtype="float")
np.concatenate([array1, array2, array3])

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 2.,  5.,  6.],
       [ 9., 10., 11.],
       [ 5.,  6.,  9.],
       [ 4., 10., 13.],
       [ 7., 14., 15.]])

# 4.3.2 La fonction vstack() et hstack()

In [110]:
# hstack() (verticale)
import numpy as np 
array1 = np.array([15,16,47])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype="float")
print(array1)
print("---")
print(array2)
print("---")
print(np.vstack([array1, array2]))
array1 = np.array([15],[16],[47])
print("---")
print(array1)
print("---")
print(array2)
print("---")
print(np.hstack([array1, array2]))

[15 16 47]
---
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
---
[[15. 16. 47.]
 [ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [116]:
# et hstack()(horizontal)
array1 = np.array([[15],[16],[47]])
print("---")
print(array1)
print("---")
print(array2)
print("---")
print(np.hstack([array1, array2]))

---
[[15]
 [16]
 [47]]
---
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
---
[[15.  1.  2.  3.]
 [16.  4.  5.  6.]
 [47.  7.  8.  9.]]


# Test

In [119]:
mean_column = np.mean(iris[:,0:3], axis = 1)
print(mean_column)
new_iris = np.insert(iris, 5,mean_column, axis=1)
print(new_iris)

[3.33333333 3.1        3.06666667 3.06666667 3.33333333 3.66666667
 3.13333333 3.3        2.9        3.16666667 3.53333333 3.26666667
 3.06666667 2.8        3.66666667 3.86666667 3.53333333 3.33333333
 3.73333333 3.46666667 3.5        3.43333333 3.06666667 3.36666667
 3.36666667 3.2        3.33333333 3.4        3.33333333 3.16666667
 3.16666667 3.43333333 3.6        3.7        3.16666667 3.13333333
 3.43333333 3.3        2.9        3.33333333 3.26666667 2.7
 2.96666667 3.36666667 3.6        3.06666667 3.5        3.06666667
 3.5        3.23333333 4.96666667 4.7        4.96666667 3.93333333
 4.63333333 4.33333333 4.76666667 3.53333333 4.7        3.93333333
 3.5        4.36666667 4.06666667 4.56666667 4.03333333 4.73333333
 4.36666667 4.2        4.3        4.         4.63333333 4.3
 4.56666667 4.53333333 4.53333333 4.66666667 4.8        4.9
 4.46666667 3.93333333 3.9        3.86666667 4.13333333 4.6
 4.3        4.63333333 4.83333333 4.33333333 4.23333333 4.
 4.16666667 4.56666667 4.133333

In [122]:
iris_mean = np.mean(iris[:,:4], axis=1)
iris_mean
print(np.insert(iris, 5,iris_mean, axis=1))

[[5.1   3.5   1.4   0.2   1.    2.55 ]
 [4.9   3.    1.4   0.2   1.    2.375]
 [4.7   3.2   1.3   0.2   1.    2.35 ]
 [4.6   3.1   1.5   0.2   1.    2.35 ]
 [5.    3.6   1.4   0.2   1.    2.55 ]
 [5.4   3.9   1.7   0.4   1.    2.85 ]
 [4.6   3.4   1.4   0.3   1.    2.425]
 [5.    3.4   1.5   0.2   1.    2.525]
 [4.4   2.9   1.4   0.2   1.    2.225]
 [4.9   3.1   1.5   0.1   1.    2.4  ]
 [5.4   3.7   1.5   0.2   1.    2.7  ]
 [4.8   3.4   1.6   0.2   1.    2.5  ]
 [4.8   3.    1.4   0.1   1.    2.325]
 [4.3   3.    1.1   0.1   1.    2.125]
 [5.8   4.    1.2   0.2   1.    2.8  ]
 [5.7   4.4   1.5   0.4   1.    3.   ]
 [5.4   3.9   1.3   0.4   1.    2.75 ]
 [5.1   3.5   1.4   0.3   1.    2.575]
 [5.7   3.8   1.7   0.3   1.    2.875]
 [5.1   3.8   1.5   0.3   1.    2.675]
 [5.4   3.4   1.7   0.2   1.    2.675]
 [5.1   3.7   1.5   0.4   1.    2.675]
 [4.6   3.6   1.    0.2   1.    2.35 ]
 [5.1   3.3   1.7   0.5   1.    2.65 ]
 [4.8   3.4   1.9   0.2   1.    2.575]
 [5.    3.    1.6   0.2  

In [123]:
moyenne = np.mean(iris, axis = 0)

print(np.insert(iris, iris.shape[0], moyenne, axis = 0 ))

[[5.1        3.5        1.4        0.2        1.        ]
 [4.9        3.         1.4        0.2        1.        ]
 [4.7        3.2        1.3        0.2        1.        ]
 [4.6        3.1        1.5        0.2        1.        ]
 [5.         3.6        1.4        0.2        1.        ]
 [5.4        3.9        1.7        0.4        1.        ]
 [4.6        3.4        1.4        0.3        1.        ]
 [5.         3.4        1.5        0.2        1.        ]
 [4.4        2.9        1.4        0.2        1.        ]
 [4.9        3.1        1.5        0.1        1.        ]
 [5.4        3.7        1.5        0.2        1.        ]
 [4.8        3.4        1.6        0.2        1.        ]
 [4.8        3.         1.4        0.1        1.        ]
 [4.3        3.         1.1        0.1        1.        ]
 [5.8        4.         1.2        0.2        1.        ]
 [5.7        4.4        1.5        0.4        1.        ]
 [5.4        3.9        1.3        0.4        1.        ]
 [5.1        3